name: Build and deploy Node.js app to Azure Web App - portfolio-v3
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: Install and build
        env:
          NODE_ENV: production
          DOMAIN: ${{ secrets.DOMAIN }}
          API_URL: ${{ secrets.API_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY }}
          NEXT_PUBLIC_EMAIL_JS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_SERVICE_ID }}
          NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID }}
          GH_READ_USER_TOKEN_PERSONAL: ${{ secrets.GH_READ_USER_TOKEN_PERSONAL }}
          DEVTO_KEY: ${{ secrets.DEVTO_KEY }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          npm ci
          npm run build

      - name: Prepare standalone package
        run: |
          cp -r .next/static .next/standalone/.next/static
          cp -r public .next/standalone/public

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "portfolio-v3"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .next/standalone
